import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Script from 'next/script'
import Link from "next/link"
import Navbar from '../Components/Navbar'
import { useDispatch, useSelector } from 'react-redux'
import loadder from "../loadder.svg"
import { useContext, useEffect } from 'react'
import { getblogs } from '../redux/actioncreators/getdata'
import Pagecontext from '../contextapi/pagecontext'
// import Dummy from '../Components/dummy'
export default function Home() {
  let dispatch=useDispatch();
  let {Blogs}=useSelector((state)=>state.Blog)
  let {page,setpage}=useContext(Pagecontext);
  useEffect(()=>{
    if (page===1) {
      dispatch(getblogs(page))
      setpage(page+1)
    }
  },[])
  return (
    <div className={styles.container}>
      {/* <style jsx >                  this is component level styling style
        {`
          .dummy{
            color:red;
          }
        `}
      </style> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs,Hunting coder,blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="sc.js" strategy="lazyOnload" /> */}
      {/* <Navbar/> */}
      {/* <Dummy/> */}

      <main className={styles.main}>
        <h1 className='dummy'>
          Hunting Coder
        </h1>

        <p className={styles.description}>

          Blog for Hunting Coders by Hunting Coders
        </p>

        <h2>Populer Blogs</h2>
        <div className={styles.grid}>
          {
          Blogs.length > 0?
          
          Blogs.filter((item, idx) => idx < 4).map(item => {

           return <Link href={`${"/Blogs/" + item._id}`} key={item._id}>
             <a className={styles.card}>
                <h3>{item.title} &rarr;</h3>
                <p>{item.metadata.split(" ").slice(0,9).join(" ")}</p>
             </a>
           </Link> 
         }):
         <Image
         src={loadder}
         alt="Picture of the author"
         width={200}
         height={200}
       />
}
        </div>
      </main>
    </div>
  )
}
