import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Script from 'next/script'
import Link from "next/link"
import Navbar from '../Components/Navbar'
// import Dummy from '../Components/dummy'
export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx >                  this is component level styling style
        {`
          .dummy{
            color:red;
          }
        `}
      </style> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs,Hunting coder,blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="sc.js" strategy="lazyOnload" /> */}
      {/* <Navbar/> */}
      {/* <Dummy/> */}

      <main className={styles.main}>
        <h1 className='dummy'>
          Hunting Coder
        </h1>

        <p className={styles.description}>

          Blog for Hunting Coders by Hunting Coders
        </p>

        <h2>Populer Blogs</h2>
        <div className={styles.grid}>
          <Link href="/Blogs/popome" >
            <a className={styles.card}>
              <h3>Documentation &rarr;</h3>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </Link>

          <Link href="/Blogs/poptwo" >
            <a className={styles.card} >
              <h3>Learn &rarr;</h3>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
          </Link>

          <Link href="/Blogs/popthree">
            <a className={styles.card} >
              <h3>Examples &rarr;</h3>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </Link>

          <Link href="/Blogs/popfour">
            <a  className={styles.card}>
              <h3>Deploy &rarr;</h3>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
